### PR TITLE
#24 added card for TedX talk to news and events page

### PR DESCRIPTION
**Pull request by 3design**
Added news card for TedX talk with link to [youtube video ](https://youtu.be/p26azhbQHWw)

### CODE REVIEW

**Comment by selineriz** [comment]
@3design I think it looks good for now

- usually Tedx posts original videos of the speakers and if they do maybe we can use that video since this one is quite short?
- i'm assuming the video is not the whole speech? I think it's best if we write a video description and if I can have the full speech I can write a description for the youtube video @christinerogers

**Comment by 3design** [comment]
Here is a screen shot of how it looks on the website if you don't have a local copy to run
FireShot Capture 101 - Global Brain Consortium - News   Events - localhost

**Comment by christinerogers** [comment]
Thanks both - -Derek please 
- [x]  merge the website change, lgtm 
- [x] update the youtube clip to include the informatino that it is Dr. Pedro Valdes-Sosa speaking 

- [ ] @selineriz good idea - please check / did you find a video on TedX Chengdu?  Let us know what you find -
@3design if Selin  has a better video then please update this news item to link there.

**Review by christinerogers — APPROVED** [review]

**Comment by selineriz** [comment]
@christinerogers I couldn't find any videos related to Tedx Chengdu I'll keep looking. It's possible they haven't uploaded it yet. The event was in April 2024 right? 
@3design i'll keep you updated if i find something

**Review by selineriz — APPROVED** [review]

**Comment by christinerogers** [comment]
@3design @selineriz there's a major typo in the text blurb.   @3design could you please fix the spelling of `consortium`. 

@selineriz when we speak in January please add this to your agenda - let's go over a plan so that more of these errors are caught consistently.

**Comment by 3design** [comment]
Typo fixed on main

**Pull request merged**
